# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# goreleaser build --auto-snapshot --clean
version: 2
project_name: static-credential-provider

builds:
  - id: static-credential-provider
    main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    ignore:
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  github:
    owner: hegerdes
    name: kube-static-credential-provider

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
