# Docs: https://kubernetes.io/docs/reference/config-api/kubelet-credentialprovider.v1/
apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
  - name: static-credential-provider
    # You can also use a config file instead of envs
    # args:[--config, <path-to-password-conf>]
    matchImages: [docker.io]
    defaultCacheDuration: "12h"
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    env:
      - name: SCP_REGISTRY_USERNAME
        value: <my-user>
      - name: SCP_REGISTRY_PASSWORD
        value: <my-password>
