name: Test Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Build-Test:
    name: Demo Build-Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["1.23", "1.24"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.version }}

      - name: Run Build
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: build --snapshot --clean

      - name: Run test
        run: go test -v
